Header header
#raw GPFPD heading, in deg
float32 fHeading
#raw GPFPD pitch, in deg
float32 fPitch
#raw GPFPD roll, in deg
float32 fRoll
#raw latitude
float64 fLatitude
#raw longitude
float64 fLongitude
#raw altitude
float32 fAltitude
#raw velocity east
float32 fVEast
#raw velocity north
float32 fVNorth
#raw velocity up
float32 fVUp
#baseline
float32 fBaseline
#NSV1
uint8 nGps1Status
#NSV2
uint8 nGps2Status
#INS status
uint8 nInsStatus

#yaw angle in ros (around axis z), in rad
#float32 fYaw
#pitch angle in ros (around axis y), in rad
#float32 fPitch
#roll angle in ros (around axis x), in rad
#float32 fRoll
#float64 fLatitude
#float64 fLongitude
#float32 fAltitude
#Vx speed in ros (around axis x, North), in m/s
#float32 fVx
#Vy speed in ros (around axis y, West), in m/s
#float32 fVy
#Vz speed in ros (around axis z, Up), in m/s
#float32 fVz
#float32 fBaseline


